repos:
-   repo: https://github.com/igrr/argparse_to_md.git
    rev: v0.4.0
    hooks:
    -   id: argparse_to_md
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace